version: '3'

services:
  xml:
    container_name: carburant_xml
    build: .
    volumes:
      - ./xml:/code
    restart: always

  mongo:
    image: mongo
    container_name: carburant_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd_root

  mongo-express:
    image: mongo-express
    container_name: carburant_mongoexpress
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pwd_root
      ME_CONFIG_MONGODB_URL: mongodb://root:pwd_root@mongo:27017/      